### ISSUE TITLE
Error opening jfr file with GC events only

### ISSUE THREAD

**Issue by ansteiner** [parttimenerd/firefox-profiler#3]
java.lang.IllegalStateException: Could not find main thread or start time
        at me.bechberger.jfrtofp.processor.BasicInformation$Companion.obtain(Processor.kt:627)
        at me.bechberger.jfrtofp.processor.BasicInformation$Companion.obtain$default(Processor.kt:557)
        at me.bechberger.jfrtofp.processor.Processor.<init>(Processor.kt:1006)
        at me.bechberger.jfrtofp.processor.SimpleProcessor.<init>(Processor.kt:1030)
        at me.bechberger.jfrtofp.FileCache.create(FileCache.kt:65)
        at me.bechberger.jfrtofp.FileCache.get(FileCache.kt:46)
        at me.bechberger.jfrtofp.server.Server.getPath(Server.java:231)
        at me.bechberger.jfrtofp.server.Server.lambda$startServer$3(Server.java:181)
[HA_G1GC_21_new_a.zip](https://github.com/parttimenerd/firefox-profiler/files/14954840/HA_G1GC_21_new_a.zip)

**Comment by parttimenerd** [comment]
Fixed in https://github.com/parttimenerd/jfrtofp/commit/3ac16fc39c2001e41868945010507b5d0eed71a0
